// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEM0HGcdw0Ggctq3KdeN4w1AhYxTa5CYo',
    appId: '1:44448392554:web:0b5e05d2a7b33dbd90f113',
    messagingSenderId: '44448392554',
    projectId: 'memoir-app-68893',
    authDomain: 'memoir-app-68893.firebaseapp.com',
    storageBucket: 'memoir-app-68893.appspot.com',
    measurementId: 'G-0RMRQY6RJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD42JsPTpE2-PJRH-iXbfbzKx2A4a1DIPA',
    appId: '1:44448392554:android:624134d442d50d0690f113',
    messagingSenderId: '44448392554',
    projectId: 'memoir-app-68893',
    storageBucket: 'memoir-app-68893.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxcmi8dNDAXkawv1AFvg2iJMxPm7_t8PM',
    appId: '1:44448392554:ios:4ba722f92398805390f113',
    messagingSenderId: '44448392554',
    projectId: 'memoir-app-68893',
    storageBucket: 'memoir-app-68893.appspot.com',
    iosClientId: '44448392554-u86pk5qiocdqoc9vs0f0fgqt8iqvkb2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.memoirApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxcmi8dNDAXkawv1AFvg2iJMxPm7_t8PM',
    appId: '1:44448392554:ios:4ba722f92398805390f113',
    messagingSenderId: '44448392554',
    projectId: 'memoir-app-68893',
    storageBucket: 'memoir-app-68893.appspot.com',
    iosClientId: '44448392554-u86pk5qiocdqoc9vs0f0fgqt8iqvkb2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.memoirApp',
  );
}
